FROM debian:buster-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
	curl \
	php7.3 \
	php7.3-cli \
	php7.3-curl \
	php7.3-gd \
	php7.3-mbstring \
	php7.3-mysql \
	php7.3-xml \
	php7.3-zip \
	unzip \
	wget
