version: '3.9'
services:
  mariadb:
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    image: mariadb:v1
    volumes:
        - db:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception

  wordpress:
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    image: wordpress:v1
    depends_on:
      - mariadb
    volumes:
        - wordpress:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env
    restart: always
    networks:
      - inception

  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx:v1
    depends_on:
      - wordpress
    volumes:
        - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    ports:
      - 443:443
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/mchliyah/data
      o: bind
  db:
    driver : local
    driver_opts:
      device: /home/mchliyah/data/db
      type: none
      o: bind

networks:
  inception:
    driver: bridge