version: '3.9'
services:
  mariadb:
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    image: mariadb:v1
    volumes:
        - db:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception

  wordpress:
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    image: wordpress:v1
    depends_on:
      - mariadb
    volumes:
        - wordpress:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      SITE_TITLE: ${SITE_TITLE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    env_file:
      - .env
    restart: always
    networks:
      - inception

  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx:v1
    depends_on:
      - wordpress
    volumes:
        - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    ports:
      - 443:443
    networks:
      - inception

  redis:
    build: 
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    container_name: redis
    image: redis:v1
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  ftps:
    build: 
      context: .
      dockerfile: requirements/bonus/ftp/Dockerfile
    container_name: ftps
    image: ftps:v1
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/mchliyah/ftp
    networks:
      - inception
    ports:
      - 21:21
      - 21000-21010:21000-21010
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    env_file:
      - .env

  adminer:
    build: 
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    container_name: adminer
    image: adminer:v1
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    ports:
      - 8000:8000
    env_file:
      - .env

  cadvisor:
    build: 
      context: .
      dockerfile: requirements/bonus/cadvisor/Dockerfile
    container_name: cadvisor
    image: cadvisor:v1
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - inception
    env_file:
      - .env


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/mchliyah/data/wordpress
      o: bind
  db:
    driver : local
    driver_opts:
      device: /home/mchliyah/data/db
      type: none
      o: bind

networks:
  inception:
    driver: bridge
    